import SideNav from "@/utils/sideNav";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
        <div className="flex min-h-screen  ">
          <div className="w-64">
            <SideNav />
          </div>
          <main className="flex-1 bg-gray-200">{children}</main>
        </div>
 
  );
}